### ISSUE TITLE
README Correction

### ISSUE THREAD

**Issue by kjenney** [jessenovotny/angular-devise-demo#2]
I found your repo while prowling Github looking for a good example of angular devise rails in action. Thanks for doing all the heavy lifting here! I just cloned it and am testing it on Docker.

For now I'm feeling lazy and haven't forked the repo but you've got a mistake in your README:

`gem 'active-model-serializer'
`
should be 

`gem 'active_model_serializers'`

Once I get this up and working I'll submit any other corrections and/or tweaks via PR.

**Comment by jessenovotny** [comment]
Good catch. I have this tutorial posted on SitePoint and someone brought it up there as well. Forgot to update the repo. Thanks
